apps/funcionarios/urls.py
from unicodedata import name
from django.urls import path
from .views import (
    FuncionarioUpdateView, 
    FuncionariosListView, 
    FuncionarioDeleteView, 
    FuncionarioCreateView,
    render_pdf_view
    )


urlpatterns = [
    path('', FuncionariosListView.as_view(), name='list_funcionarios'),
    path('edit/<int:pk>/', FuncionarioUpdateView.as_view(), name='edit_funcionario'),
    path('delete/<int:pk>/', FuncionarioDeleteView.as_view(), name='delete_funcionario'),
    path('create/', FuncionarioCreateView.as_view(), name='create_funcionario'),
    path('pdf-relatorio/<int:pk>/', render_pdf_view, name='pdf_relatorio'),
    
]

core/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home')
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from rest_framework import routers
from core import views
from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import RegistroHoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/horas-extras', RegistroHoraExtraViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls'), name='funcionarios'),
    path('empresas/', include('apps.empresas.urls'), name='empresas'),
    path('departamentos/', include('apps.departamentos.urls'), name='departamentos'),
    path('documentos/', include('apps.documentos.urls'), name='documentos'),
    path('horas-extras/', include('apps.registro_hora_extra.urls'), name='hora_extras'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from statistics import mode
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse


class Documento(models.Model):
    descricao = models.CharField('Descrição', max_length=70, help_text='Descrição do Documento')
    # um documento pode pertencer para um empregado
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT) 
    documento = models.FileField('Documento', upload_to='documentos')


    def __str__(self):
        return self.descricao

    
    def get_absolute_url(self):
        return reverse('edit_funcionario', args=[self.pertence.id])
        

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.urls import reverse
from django.db.models import Sum
from stdimage import StdImageField



class Funcionario(models.Model):
    nome = models.CharField('Funcionario', max_length=100, help_text='Nome Funcionario')
    user = models.OneToOneField(User, models.PROTECT)
    departamentos = models.ManyToManyField(Departamento) # um funcionario pode estar em vários departamentos
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    foto = StdImageField(upload_to='foto_perfil', blank=True, variations= { 
        'thumbnail' :  { "width" :  100 ,  "height" :  100 ,  "crop" :  True } 
    })
    de_ferias = models.BooleanField(default=False)
    

    def __str__(self) :
        return self.nome


    def get_absolute_url(self):
        return reverse('list_funcionarios')


    @property
    def total_hora_extra(self):
        total = self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum']
        return total or 0


    @property
    def hora_utilizada(self):
        hora = self.registrohoraextra_set.filter(utilizada=True)
        return hora
        

apps/registro_hora_extra/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse


class RegistroHoraExtra(models.Model):
    motivo = models.CharField('Motivo', max_length=100, help_text='Motivo da Hora Extra')
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)


    def __str__(self):
        return self.motivo


    def get_absolute_url(self):
        return reverse('edit_funcionario', args=[self.funcionario.id])

apps/funcionarios/api/views.py
from .serializers import FuncinarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


class FuncionarioViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Funcionario.objects.all()
    serializer_class = FuncinarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps/funcionarios/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Funcionario
from django.contrib.auth.models import User

#lib pdf
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa



class FuncionariosListView(ListView):
    model = Funcionario
    template_name = 'funcionario_list.html'

    
    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)
    

class FuncionarioUpdateView(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos', 'foto', 'de_ferias']
    template_name = 'funcionario_edit.html'


class FuncionarioDeleteView(DeleteView):
    model = Funcionario
    fields = ['nome', 'departamentos']
    template_name = 'funcionario_delete.html'
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreateView(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos', 'foto', 'de_ferias']
    template_name = 'funcionario_create.html'


    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreateView, self).form_valid(form)


def render_pdf_view(request, *args, **kwargs):
    template_path = 'pdf_funcionario.html'
    funcionario = Funcionario.objects.get(id=kwargs['pk'])
    context = {'funcionario': funcionario}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="funcionario.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
    html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

apps/funcionarios/templates/funcionario_create.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %} 
    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit">Salvar</button>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionario_delete.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %} 
    <form method="post">
        {% csrf_token %}
        <p>Tem certeza que deseja deletear "{{ object }}"?</p>
        {{ form|bootstrap }}
        <button class=" btn btn-danger" type="submit">Deletar</button>
        </a>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionario_edit.html
{% extends 'base.html' %}
{% load bootstrap %}


{% block main %} 
    <img src="{{ object.foto.thumbnail.url }}" alt="">
    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
    <br>
    <h4>Documentos</h4>
    {% for documento in object.documento_set.all %}
        <ul>
            <li><a href="{{ documento.documento.url }}" target="_blank">{{ documento }}</a></li> 
        </ul>
    {% endfor %}
    <a href="{% url 'create_documento' object.id %}" class="btn btn-info">Adicionar Documento</a>
    <br>
    <br>
    <h4>Registro Hora Extra</h4>
    {% for registro in object.registrohoraextra_set.all %}
        {% if registro.utilizada == True %}
            <ul>
                <a href="{% url 'edit_hora_extra' registro.id %}">
                    <li style="color: darkgreen; font-weight: bolder;">
                        {{ registro.motivo }} | horas {{registro.horas}} - Horas já utilizada
                    </li>
                </a>
            </ul>
        {% else %}    
            <ul>
                <a href="{% url 'edit_hora_extra' registro.id %}">
                    <li >
                        {{ registro.motivo }} | horas {{registro.horas}}
                    </li>
                </a>
            </ul>
        {% endif %}
    {% endfor %}
    
    <h5>Total Hora Extra: {{ object.total_hora_extra }}</h5>

    <a href="{% url 'pdf_relatorio' object.id %}" class="btn btn-info" target="_blank">Gerar Relatorio PDF</a>
{% endblock %}

apps/funcionarios/templates/funcionario_list.html
{% extends 'base.html' %}

{% block main %} 
    List <br>
    {% for funcionario in object_list %}
        {{ funcionario }}
        <a href="{% url 'edit_funcionario' funcionario.id %}"><button class="btn btn-warning">Editar</button></a>
        <a href="{% url 'delete_funcionario' funcionario.id %}"><button class="btn btn-danger">Deletar</button></a>
        <br><br>
    {% endfor %}
        <a href="{% url 'create_funcionario' %}" class="btn btn-info" >Novo</a>
    {% endblock %}

apps/funcionarios/templates/pdf_funcionario.html
{% extends 'base.html' %}
{% load bootstrap %}


{% block main %} 
    <br>
    <img src="{{ funcionario.foto.path }}" alt="">
    <h1>Funcionario: {{ funcionario.nome }}</h1>
    <h2>Empresa: {{ funcionario.empresa }}</h2>
    <h4>Departamento</h4>
    {% for departamento in funcionario.departamentos_set.all %}
        <ul>
            <li>{{ departamento }}</li>
        </ul>
    {% endfor %}
    <h4>Documentos</h4>
    {% for documento in funcionario.documento_set.all %}
        <ul>
            <li>{{ documento }}</li> 
        </ul>
    {% endfor %}
    <br>
    <br>
    <h4>Registro Hora Extra</h4>
    {% for registro in funcionario.registrohoraextra_set.all %}
        {% if registro.utilizada == True %}
            <ul>
                <li style="color: darkgreen; font-weight: bolder;">
                    {{ registro.motivo }} | horas {{registro.horas}} - Horas já utilizada
                </li>
            </ul>
        {% else %}    
            <ul>
                <li >
                    {{ registro.motivo }} | horas {{registro.horas}}
                </li>
            </ul>
        {% endif %}
    {% endfor %}
    
    <h5>Total Hora Extra: {{ funcionario.total_hora_extra }}</h5>

{% endblock %}